
if(window['dojo'])dojo.provide('dwr.engine');if(typeof window['dwr']=='undefined'){dwr={};}
(function(){dwr.engine={};dwr.engine.setErrorHandler=function(handler){dwr.engine._errorHandler=handler;};dwr.engine.setWarningHandler=function(handler){dwr.engine._warningHandler=handler;};dwr.engine.setTextHtmlHandler=function(handler){dwr.engine._textHtmlHandler=handler;};dwr.engine.setTimeout=function(timeout){dwr.engine._timeout=timeout;};dwr.engine.setPreHook=function(handler){dwr.engine._preHook=handler;};dwr.engine.setPostHook=function(handler){dwr.engine._postHook=handler;};dwr.engine.setHeaders=function(headers){dwr.engine._headers=headers;};dwr.engine.setParameters=function(parameters){dwr.engine._parameters=parameters;};dwr.engine.setOrdered=function(ordered){dwr.engine._ordered=ordered;};dwr.engine.setAsync=function(async){dwr.engine._async=async;};dwr.engine.setActiveReverseAjax=function(activeReverseAjax){if(activeReverseAjax){if(dwr.engine._activeReverseAjax)return;dwr.engine._activeReverseAjax=true;dwr.engine._poll();}
else{if(dwr.engine._activeReverseAjax&&dwr.engine._pollReq){dwr.engine._pollReq.abort();}
dwr.engine._activeReverseAjax=false;}};dwr.engine.setNotifyServerOnPageUnload=function(notify){dwr.engine._isNotifyServerOnPageUnload=notify;};dwr.engine.defaultErrorHandler=function(message,ex){dwr.engine._debug("Error: "+ex.name+", "+ex.message,true);if(message==null||message=="")alert("A server error has occurred.");else if(message.indexOf("0x80040111")!=-1)dwr.engine._debug(message);else alert(message);};dwr.engine.defaultWarningHandler=function(message,ex){dwr.engine._debug(message);};dwr.engine.beginBatch=function(){if(dwr.engine._batch){dwr.engine._handleError(null,{name:"dwr.engine.batchBegun",message:"Batch already begun"});return;}
dwr.engine._batch=dwr.engine.batch.create();};dwr.engine.endBatch=function(options){var batch=dwr.engine._batch;if(batch==null){dwr.engine._handleError(null,{name:"dwr.engine.batchNotBegun",message:"No batch in progress"});return;}
dwr.engine._batch=null;if(batch.map.callCount==0){return;}
if(options){dwr.engine.batch.merge(batch,options);}
if(dwr.engine._ordered&&dwr.engine._batchesLength!=0){dwr.engine._batchQueue[dwr.engine._batchQueue.length]=batch;}
else{return dwr.engine.transport.send(batch);}};dwr.engine.openInDownload=function(data){var div=document.createElement("div");document.body.appendChild(div);div.innerHTML="<iframe width='0' height='0' scrolling='no' frameborder='0' src='"+data+"'></iframe>";};dwr.version={major:parseInt("${versionMajor}"),minor:parseInt("${versionMinor}"),revision:parseInt("${versionRevision}"),build:parseInt("${versionBuild}"),title:"${versionTitle}",label:"${versionLabel}"};dwr.engine._sessionCookieName="JSESSIONID";dwr.engine._allowGetForSafariButMakeForgeryEasier="";dwr.engine._scriptTagProtection="throw 'allowScriptTagRemoting is false.';";dwr.engine._pathToDwrServlet=""+JAWR.jawr_dwr_path+"";dwr.engine._pollWithXhr="false";dwr.engine._ModePlainCall="/call/plaincall/";dwr.engine._ModePlainPoll="/call/plainpoll/";dwr.engine._ModeHtmlCall="/call/htmlcall/";dwr.engine._ModeHtmlPoll="/call/htmlpoll/";dwr.engine._async=Boolean("true");dwr.engine._scriptSessionId=null;dwr.engine._preHook=null;dwr.engine._postHook=null;dwr.engine._batches={};dwr.engine._batchesLength=0;dwr.engine._batchQueue=[];dwr.engine._ordered=true;dwr.engine._batch=null;dwr.engine._timeout=0;dwr.engine._activeReverseAjax=false;dwr.engine._pollReq=null;dwr.engine._pollCometInterval=200;dwr.engine._pollRetries=0;dwr.engine._maxPollRetries=10;dwr.engine._retryIntervals=[2,5,10,60,300];dwr.engine._textHtmlHandler=null;dwr.engine._headers=null;dwr.engine._parameters=null;dwr.engine._nextBatchId=0;dwr.engine._propnames=["async","timeout","errorHandler","warningHandler","textHtmlHandler"];dwr.engine._partialResponseNo=0;dwr.engine._partialResponseYes=1;dwr.engine._partialResponseFlush=2;dwr.engine._isNotifyServerOnPageUnload=false;if(typeof dwr.engine['_mappedClasses']=='undefined'){dwr.engine._mappedClasses={};}
dwr.engine._getHttpSessionId=function(){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=cookies[i];while(cookie.charAt(0)==' ')cookie=cookie.substring(1,cookie.length);if(cookie.indexOf(dwr.engine._sessionCookieName+"=")==0){return cookie.substring(dwr.engine._sessionCookieName.length+1,cookie.length);}}
return"";};dwr.engine._errorHandler=dwr.engine.defaultErrorHandler;dwr.engine._warningHandler=dwr.engine.defaultWarningHandler;dwr.engine._postSeperator="\n";dwr.engine._defaultInterceptor=function(data){return data;};dwr.engine._urlRewriteHandler=dwr.engine._defaultInterceptor;dwr.engine._contentRewriteHandler=dwr.engine._defaultInterceptor;dwr.engine._replyRewriteHandler=dwr.engine._defaultInterceptor;dwr.engine._unloading=false;dwr.engine._unloader=function(){dwr.engine._unloading=true;dwr.engine._batchQueue.length=0;var batch;for(var batchId in dwr.engine._batches){batch=dwr.engine._batches[batchId];if(batch&&batch.map){if(batch.req){batch.req.abort();}}}
if(dwr.engine._isNotifyServerOnPageUnload){dwr.engine._debug("calling unloader for: "+dwr.engine._scriptSessionId);batch={map:{callCount:1,'c0-scriptName':'__System','c0-methodName':'pageUnloaded','c0-id':0},paramCount:0,isPoll:false,async:true,headers:{},preHooks:[],postHooks:[],timeout:dwr.engine._timeout,errorHandler:null,warningHandler:null,textHtmlHandler:null,path:dwr.engine._pathToDwrServlet,handlers:[{exceptionHandler:null,callback:null}]};dwr.engine.transport.send(batch);dwr.engine._isNotifyServerOnPageUnload=false;}};if(!dwr.engine.isJaxerServer){if(window.addEventListener)window.addEventListener('unload',dwr.engine._unloader,false);else if(window.attachEvent)window.attachEvent('onunload',dwr.engine._unloader);}
dwr.engine._execute=function(path,scriptName,methodName,args){var singleShot=false;if(dwr.engine._batch==null){dwr.engine.beginBatch();singleShot=true;}
var batch=dwr.engine._batch;if(batch.path==null){batch.path=path;}
else{if(batch.path!=path){dwr.engine._handleError(batch,{name:"dwr.engine.multipleServlets",message:"Can't batch requests to multiple DWR Servlets."});return;}}
dwr.engine.batch.addCall(batch,scriptName,methodName,args);batch.map.callCount++;if(singleShot){return dwr.engine.endBatch();}};dwr.engine._poll=function(){if(!dwr.engine._activeReverseAjax){return;}
var batch=dwr.engine.batch.createPoll();dwr.engine.transport.send(batch);};dwr.engine._pollErrorHandler=function(msg,ex){if(dwr.engine._pollRetries>dwr.engine._maxPollRetries){dwr.engine._activeReverseAjax=false;dwr.engine._debug("Reverse Ajax poll failed (retries="+dwr.engine._pollRetries+"). Giving Up: "+ex.name+" : "+ex.message);dwr.engine._debug("Giving up.");return;}
var index=dwr.engine._pollRetries;if(index>=dwr.engine._retryIntervals.length){index=dwr.engine._retryIntervals.length-1;}
dwr.engine._debug("Reverse Ajax poll failed (retries="+dwr.engine._pollRetries+"). Trying again in "+dwr.engine._retryIntervals[index]+"s: "+ex.name+" : "+ex.message);setTimeout(dwr.engine._poll,1000*dwr.engine._retryIntervals[index]);dwr.engine._pollRetries++;};dwr.engine._eval=function(script){if(script==null){return null;}
if(script==""){dwr.engine._debug("Warning: blank script",true);return null;}
return eval(script);};dwr.engine._callPostHooks=function(batch){if(batch.postHooks){for(var i=0;i<batch.postHooks.length;i++){batch.postHooks[i]();}
batch.postHooks=null;}};dwr.engine._handleError=function(batch,ex){if(typeof ex=="string")ex={name:"unknown",message:ex};if(ex.message==null)ex.message="";if(ex.name==null)ex.name="unknown";if(batch&&typeof batch.errorHandler=="function")batch.errorHandler(ex.message,ex);else if(dwr.engine._errorHandler)dwr.engine._errorHandler(ex.message,ex);if(batch)dwr.engine.batch.remove(batch);};dwr.engine._handleWarning=function(batch,ex){if(typeof ex=="string")ex={name:"unknown",message:ex};if(ex.message==null)ex.message="";if(ex.name==null)ex.name="unknown";if(batch&&typeof batch.warningHandler=="function")batch.warningHandler(ex.message,ex);else if(dwr.engine._warningHandler)dwr.engine._warningHandler(ex.message,ex);if(batch)dwr.engine.batch.remove(batch);};dwr.engine._debug=function(message,stacktrace){var written=false;try{if(window.console){if(stacktrace&&window.console.trace)window.console.trace();window.console.log(message);written=true;}
else if(window.opera&&window.opera.postError){window.opera.postError(message);written=true;}
else if(window.Jaxer&&Jaxer.isOnServer){Jaxer.Log.info(message);written=true;}}
catch(ex){}
if(!written){var debug=document.getElementById("dwr-debug");if(debug){var contents=message+"<br/>"+debug.innerHTML;if(contents.length>2048)contents=contents.substring(0,2048);debug.innerHTML=contents;}}};dwr.engine.remote={handleCallback:function(batchId,callId,reply){var batch=dwr.engine._batches[batchId];if(batch==null){dwr.engine._debug("Warning: batch == null in remoteHandleCallback for batchId="+batchId,true);return;}
batch.reply=reply;try{var handlers=batch.handlers[callId];if(!handlers){dwr.engine._debug("Warning: Missing handlers. callId="+callId,true);}
else{batch.handlers[callId].completed=true;if(typeof handlers.callback=="function"){handlers.callback.apply(handlers.callbackScope,[reply,handlers.callbackArg]);}}}
catch(ex){dwr.engine._handleError(batch,ex);}},handleFunctionCall:function(id,args){var func=dwr.engine.serialize.remoteFunctions[id];func.apply(window,args);},handleObjectCall:function(id,methodName,args){var obj=dwr.engine.serialize.remoteFunctions[id];obj[methodName].apply(obj,args);},handleSetCall:function(id,propertyName,data){var obj=dwr.engine.serialize.remoteFunctions[id];obj[propertyName]=data;},handleFunctionClose:function(id){delete dwr.engine.serialize.remoteFunctions[id];},handleException:function(batchId,callId,ex){var batch=dwr.engine._batches[batchId];if(batch==null){dwr.engine._debug("Warning: null batch in remoteHandleException",true);return;}
var handlers=batch.handlers[callId];batch.handlers[callId].completed=true;if(handlers==null){dwr.engine._debug("Warning: null handlers in remoteHandleException",true);return;}
if(ex.message==undefined){ex.message="";}
if(typeof handlers.exceptionHandler=="function"){handlers.exceptionHandler.call(handlers.exceptionScope,ex.message,ex,handlers.exceptionArg);}
else if(typeof batch.errorHandler=="function"){batch.errorHandler(ex.message,ex);}},handleBatchException:function(ex,batchId){var searchBatch=(dwr.engine._receivedBatch==null&&batchId!=null);if(searchBatch){dwr.engine._receivedBatch=dwr.engine._batches[batchId];}
if(ex.message==undefined)ex.message="";dwr.engine._handleError(dwr.engine._receivedBatch,ex);if(searchBatch){dwr.engine._receivedBatch=null;dwr.engine.batch.remove(dwr.engine._batches[batchId]);}},handleNewScriptSession:function(newSessionId){if(dwr.engine._scriptSessionId!=null){dwr.engine._debug("Server side script session id timed out. New session automatically created");}
dwr.engine._scriptSessionId=newSessionId;},handleNewWindowName:function(windowName){dwr.engine._debug("Setting new window name: "+windowName);if(window.name!=null&&window.name!=""){dwr.engine._debug("- Warning: This will override existing name of: "+window.name);}
window.name=windowName;},handleForeign:function(windowName,script){var foreign=window.open(null,windowName);if(foreign!=null){if(foreign.dwr!=null){foreign.dwr.engine._eval(script);}
else{dwr.engine._debug("Found window, but DWR did not exist in it");}}
else{dwr.engine._debug("Could not find window");}},pollCometDisabled:function(ex,batchId){dwr.engine.setActiveReverseAjax(false);var searchBatch=(dwr.engine._receivedBatch==null&&batchId!=null);if(searchBatch){dwr.engine._receivedBatch=dwr.engine._batches[batchId];}
if(ex.message==undefined){ex.message="";}
dwr.engine._handleError(dwr.engine._receivedBatch,ex);if(searchBatch){dwr.engine._receivedBatch=null;dwr.engine.batch.remove(dwr.engine._batches[batchId]);}},newObject:function(dwrClassName,memberMap){var classfunc=dwr.engine._mappedClasses[dwrClassName];if(classfunc&&classfunc.createFromMap){return classfunc.createFromMap(memberMap);}
else{memberMap.$dwrClassName=dwrClassName;return memberMap;}}};dwr.engine.serialize={domDocument:["Msxml2.DOMDocument.6.0","Msxml2.DOMDocument.5.0","Msxml2.DOMDocument.4.0","Msxml2.DOMDocument.3.0","MSXML2.DOMDocument","MSXML.DOMDocument","Microsoft.XMLDOM"],remoteFunctions:{},funcId:0,toDomElement:function(xml){return dwr.engine.serialize.toDomDocument(xml).documentElement;},toDomDocument:function(xml){var dom;if(window.DOMParser){var parser=new DOMParser();dom=parser.parseFromString(xml,"text/xml");if(!dom.documentElement||dom.documentElement.tagName=="parsererror"){var message=dom.documentElement.firstChild.data;message+="\n"+dom.documentElement.firstChild.nextSibling.firstChild.data;throw message;}
return dom;}
else if(window.ActiveXObject){dom=dwr.engine.util.newActiveXObject(dwr.engine.serialize.domDocument);dom.loadXML(xml);return dom;}
else{var div=document.createElement("div");div.innerHTML=xml;return div;}},convert:function(batch,referto,data,name,depth){if(data==null){batch.map[name]="null:null";return;}
switch(typeof data){case"boolean":batch.map[name]="boolean:"+data;break;case"number":batch.map[name]="number:"+data;break;case"string":batch.map[name]="string:"+encodeURIComponent(data);break;case"object":var ref=dwr.engine.serialize.lookup(referto,data,name);var objstr=Object.prototype.toString.call(data);if(data.$dwrByRef)batch.map[name]=dwr.engine.serialize.convertByReference(batch,referto,data,name,depth+1);else if(ref!=null)batch.map[name]=ref;else if(objstr=="[object String]")batch.map[name]="string:"+encodeURIComponent(data);else if(objstr=="[object Boolean]")batch.map[name]="boolean:"+data;else if(objstr=="[object Number]")batch.map[name]="number:"+data;else if(objstr=="[object Date]")batch.map[name]="date:"+data.getTime();else if(objstr=="[object Array]")batch.map[name]=dwr.engine.serialize.convertArray(batch,referto,data,name,depth+1);else if(data&&data.tagName&&data.tagName.toLowerCase()=="input"&&data.type&&data.type.toLowerCase()=="file"){batch.fileUpload=true;batch.map[name]=data;}
else{if(data.nodeName&&data.nodeType){batch.map[name]=dwr.engine.serialize.convertXml(batch,referto,data,name,depth+1);}
else{batch.map[name]=dwr.engine.serialize.convertObject(batch,referto,data,name,depth+1);}}
break;case"function":if(depth==0){batch.map[name]=dwr.engine.serialize.convertByReference(batch,referto,data,name,depth+1);}
break;default:dwr.engine._handleWarning(null,{name:"dwr.engine.unexpectedType",message:"Unexpected type: "+typeof data+", attempting default converter."});batch.map[name]="default:"+data;break;}},convertByReference:function(batch,referto,data,name,depth){var funcId="f"+dwr.engine.serialize.funcId;dwr.engine.serialize.remoteFunctions[funcId]=data;dwr.engine.serialize.funcId++;return"byref:"+funcId;},convertArray:function(batch,referto,data,name,depth){var childName,i;if(dwr.engine.isIE<=7){var buf=["array:["];for(i=0;i<data.length;i++){if(i!=0)buf.push(",");batch.paramCount++;childName="c"+dwr.engine._batch.map.callCount+"-e"+batch.paramCount;dwr.engine.serialize.convert(batch,referto,data[i],childName,depth+1);buf.push("reference:");buf.push(childName);}
buf.push("]");reply=buf.join("");}
else{var reply="array:[";for(i=0;i<data.length;i++){if(i!=0)reply+=",";batch.paramCount++;childName="c"+dwr.engine._batch.map.callCount+"-e"+batch.paramCount;dwr.engine.serialize.convert(batch,referto,data[i],childName,depth+1);reply+="reference:";reply+=childName;}
reply+="]";}
return reply;},convertObject:function(batch,referto,data,name,depth){var reply="Object_"+dwr.engine.serialize.getObjectClassName(data)+":{";var elementset=(data.constructor&&data.constructor.$dwrClassMembers?data.constructor.$dwrClassMembers:data);var element;for(element in elementset){if(typeof data[element]!="function"){batch.paramCount++;var childName="c"+dwr.engine._batch.map.callCount+"-e"+batch.paramCount;dwr.engine.serialize.convert(batch,referto,data[element],childName,depth+1);reply+=encodeURIComponent(element)+":reference:"+childName+", ";}}
if(reply.substring(reply.length-2)==", "){reply=reply.substring(0,reply.length-2);}
reply+="}";return reply;},convertXml:function(batch,referto,data,name,depth){var output;if(window.XMLSerializer)output=new XMLSerializer().serializeToString(data);else if(data.toXml)output=data.toXml;else output=data.innerHTML;return"xml:"+encodeURIComponent(output);},lookup:function(referto,data,name){var lookup;for(var i=0;i<referto.length;i++){if(referto[i].data==data){lookup=referto[i];break;}}
if(lookup){return"reference:"+lookup.name;}
referto.push({data:data,name:name});return null;},getObjectClassName:function(obj){if(obj.$dwrClassName)
return obj.$dwrClassName;else if(obj.constructor&&obj.constructor.$dwrClassName)
return obj.constructor.$dwrClassName;else
return"Object";}};dwr.engine.transport={send:function(batch){dwr.engine.batch.prepareToSend(batch);var isCrossDomain=false;if(batch.path==null){batch.path=dwr.engine._pathToDwrServlet;}
if(batch.path.indexOf("http://")==0||batch.path.indexOf("https://")==0){var dwrShortPath=dwr.engine._pathToDwrServlet.split("/",3).join("/");var hrefShortPath=window.location.href.split("/",3).join("/");isCrossDomain=(dwrShortPath!=hrefShortPath);}
if(batch.fileUpload){if(isCrossDomain){throw new Error("Cross domain file uploads are not possible with this release of DWR");}
batch.transport=dwr.engine.transport.iframe;}
else if(isCrossDomain&&!dwr.engine.isJaxerServer){batch.transport=dwr.engine.transport.scriptTag;}
else{batch.transport=dwr.engine.transport.xhr;}
return batch.transport.send(batch);},remove:function(batch){dwr.engine.transport.iframe.remove(batch);dwr.engine.transport.xhr.remove(batch);},abort:function(batch){if(batch&&!batch.completed){dwr.engine.batch.remove(batch);if(batch.req){batch.req.abort();}
dwr.engine.transport.remove(batch);dwr.engine._handleError(batch,{name:"dwr.engine.timeout",message:"Timeout"});}},xhr:{httpMethod:"POST",XMLHTTP:["Msxml2.XMLHTTP.6.0","Msxml2.XMLHTTP.5.0","Msxml2.XMLHTTP.4.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],send:function(batch){if(batch.isPoll){batch.map.partialResponse=dwr.engine._partialResponseYes;}
if(batch.isPoll&&dwr.engine._pollWithXhr=="true"){batch.map.partialResponse=dwr.engine._partialResponseNo;}
if(batch.isPoll&&dwr.engine.isIE){batch.map.partialResponse=dwr.engine._partialResponseNo;}
if(window.XMLHttpRequest){batch.req=new XMLHttpRequest();}
else if(window.ActiveXObject){batch.req=dwr.engine.util.newActiveXObject(dwr.engine.transport.xhr.XMLHTTP);}
if(batch.async==true){batch.req.onreadystatechange=function(){if(typeof dwr!='undefined'){dwr.engine.transport.xhr.stateChange(batch);}};}
if(batch.isPoll){dwr.engine._pollReq=batch.req;if(!dwr.engine.isIE)batch.req.batch=batch;}
httpMethod=dwr.engine.transport.xhr.httpMethod;var indexSafari=navigator.userAgent.indexOf("Safari/");if(indexSafari>=0){var version=navigator.userAgent.substring(indexSafari+7);if(parseInt(version,10)<400){if(dwr.engine._allowGetForSafariButMakeForgeryEasier=="true"){httpMethod="GET";}
else{dwr.engine._handleWarning(batch,{name:"dwr.engine.oldSafari",message:"Safari GET support disabled. See getahead.org/dwr/server/servlet and allowGetForSafariButMakeForgeryEasier."});}}}
batch.mode=batch.isPoll?dwr.engine._ModePlainPoll:dwr.engine._ModePlainCall;var request=dwr.engine.batch.constructRequest(batch,httpMethod);try{batch.req.open(httpMethod,request.url,batch.async);try{for(var prop in batch.headers){var value=batch.headers[prop];if(typeof value=="string"){batch.req.setRequestHeader(prop,value);}}
if(!batch.headers["Content-Type"]){batch.req.setRequestHeader("Content-Type","text/plain");}}
catch(ex){dwr.engine._handleWarning(batch,ex);}
batch.req.send(request.body);if(batch.async==false){dwr.engine.transport.xhr.stateChange(batch);}}
catch(ex){dwr.engine._handleError(batch,ex);}
if(batch.isPoll&&batch.map.partialResponse==dwr.engine._partialResponseYes){dwr.engine.transport.xhr.checkCometPoll();}
return batch.reply;},stateChange:function(batch){var toEval;if(batch.completed){dwr.engine._debug("Error: _stateChange() with batch.completed");return;}
var req=batch.req;try{var readyState=req.readyState;var notReady=(req.readyState!=4);if(notReady){return;}}
catch(ex){dwr.engine._handleWarning(batch,ex);dwr.engine.batch.remove(batch);return;}
if(dwr.engine._unloading&&!dwr.engine.isJaxerServer){dwr.engine._debug("Ignoring reply from server as page is unloading.");return;}
try{var reply=req.responseText;reply=dwr.engine._replyRewriteHandler(reply);var status=req.status;if(reply==null||reply==""){dwr.engine._handleWarning(batch,{name:"dwr.engine.missingData",message:"No data received from server"});}
else if(status!=200){dwr.engine._handleError(batch,{name:"dwr.engine.http."+status,message:req.statusText});}
else{var contentType=req.getResponseHeader("Content-Type");if(dwr.engine.isJaxerServer){contentType="text/javascript";}
if(!contentType.match(/^text\/plain/)&&!contentType.match(/^text\/javascript/)){if(contentType.match(/^text\/html/)&&typeof batch.textHtmlHandler=="function"){batch.textHtmlHandler({status:status,responseText:reply,contentType:contentType});}
else{dwr.engine._handleWarning(batch,{name:"dwr.engine.invalidMimeType",message:"Invalid content type: '"+contentType+"'"});}}
else{if(batch.isPoll&&batch.map.partialResponse==dwr.engine._partialResponseYes){dwr.engine.transport.xhr.processCometResponse(reply,batch);}
else{if(reply.search("//#DWR")==-1){dwr.engine._handleWarning(batch,{name:"dwr.engine.invalidReply",message:"Invalid reply from server"});}
else{toEval=reply;}}}}}
catch(ex){dwr.engine._handleWarning(batch,ex);}
dwr.engine._callPostHooks(batch);dwr.engine._receivedBatch=batch;if(toEval!=null)toEval=toEval.replace(dwr.engine._scriptTagProtection,"");dwr.engine._eval(toEval);dwr.engine._receivedBatch=null;dwr.engine.batch.validate(batch);if(!batch.completed)dwr.engine.batch.remove(batch);},checkCometPoll:function(){if(dwr.engine._pollReq){var req=dwr.engine._pollReq;var text=req.responseText;if(text!=null){dwr.engine.transport.xhr.processCometResponse(text,req.batch);}}
if(dwr.engine._pollReq){setTimeout(dwr.engine.transport.xhr.checkCometPoll,dwr.engine._pollCometInterval);}},processCometResponse:function(response,batch){if(batch.charsProcessed==response.length)return;if(response.length==0){batch.charsProcessed=0;return;}
var firstStartTag=response.indexOf("//#DWR-START#",batch.charsProcessed);if(firstStartTag==-1){batch.charsProcessed=response.length;return;}
var lastEndTag=response.lastIndexOf("//#DWR-END#");if(lastEndTag==-1){return;}
if(response.charCodeAt(lastEndTag+11)==13&&response.charCodeAt(lastEndTag+12)==10){batch.charsProcessed=lastEndTag+13;}
else{batch.charsProcessed=lastEndTag+11;}
var exec=response.substring(firstStartTag+13,lastEndTag);try{dwr.engine._receivedBatch=batch;dwr.engine._eval(exec);dwr.engine._receivedBatch=null;}
catch(ex){if(dwr!=null){dwr.engine._handleError(batch,ex);}}},remove:function(batch){if(batch.req){if(batch.req==dwr.engine._pollReq)dwr.engine._pollReq=null;delete batch.req;}}},iframe:{send:function(batch){if(batch.fileUpload){batch.httpMethod="POST";batch.encType="multipart/form-data";}
var idname=dwr.engine.transport.iframe.getId(batch);batch.div=document.createElement("div");document.body.appendChild(batch.div);batch.div.innerHTML="<iframe src='javascript:void(0)' frameborder='0' style='width:0px;height:0px;border:0;' id='"+idname+"' name='"+idname+"' onload='dwr.engine.transport.iframe.loadingComplete("+batch.map.batchId+");'></iframe>";batch.document=document;dwr.engine.transport.iframe.beginLoader(batch,idname);},getId:function(batch){return batch.isPoll?"dwr-if-poll-"+batch.map.batchId:"dwr-if-"+batch.map.batchId;},beginLoader:function(batch,idname){batch.iframe=batch.document.getElementById(idname);batch.iframe.batch=batch;batch.mode=batch.isPoll?dwr.engine._ModeHtmlPoll:dwr.engine._ModeHtmlCall;if(batch.isPoll)dwr.engine._outstandingIFrames.push(batch.iframe);var request=dwr.engine.batch.constructRequest(batch,batch.httpMethod);if(batch.httpMethod=="GET"){batch.iframe.setAttribute("src",request.url);}
else{var formHtml="<form id='dwr-form' action='"+request.url+"' target='"+idname+"' style='display:none;' method='"+batch.httpMethod+"'";if(batch.encType)formHtml+=" enctype='"+batch.encType+"'";formHtml+="></form>";var div=batch.document.createElement("div");div.innerHTML=formHtml;batch.form=div.firstChild;for(var prop in batch.map){var value=batch.map[prop];if(typeof value!="function"){if(value.tagName&&value.tagName.toLowerCase()=="input"&&value.type&&value.type.toLowerCase()=="file"){var clone=value.cloneNode(true);value.removeAttribute("id",prop);value.setAttribute("name",prop);value.parentNode.insertBefore(clone,value);value.parentNode.removeChild(value);batch.form.appendChild(value);}else{var formInput=batch.document.createElement("input");formInput.setAttribute("type","hidden");formInput.setAttribute("name",prop);formInput.setAttribute("value",value);batch.form.appendChild(formInput);}}}
batch.document.body.appendChild(batch.form);batch.form.submit();}},loadingComplete:function(batchId){var batch=dwr.engine._batches[batchId];if(batch)dwr.engine.batch.validate(batch);},remote:{beginIFrameResponse:function(iframe,batchId){if(iframe!=null)dwr.engine._receivedBatch=iframe.batch;dwr.engine._callPostHooks(dwr.engine._receivedBatch);},endIFrameResponse:function(batchId){dwr.engine.batch.remove(dwr.engine._receivedBatch);dwr.engine._receivedBatch=null;}},remove:function(batch){if(batch.div){batch.div.parentNode.removeChild(batch.div);}
if(batch.iframe){batch.iframe.parentNode.removeChild(batch.iframe);}
if(batch.form){batch.form.parentNode.removeChild(batch.form);}}},scriptTag:{send:function(batch){batch.mode=batch.isPoll?dwr.engine._ModePlainPoll:dwr.engine._ModePlainCall;var request=dwr.engine.batch.constructRequest(batch,"GET");if(document.body){batch.script=document.createElement("script");batch.script.id="dwr-st-"+batch.map.batchId;batch.script.src=request.url;batch.script.type="text/javascript";document.body.appendChild(batch.script);}
else{document.writeln("<scr"+"ipt type='text/javascript' id='dwr-st-"+batch.map["c0-id"]+"' src='"+request.url+"'> </scr"+"ipt>");}}},htmlfile:{send:function(batch){var idname=dwr.engine.transport.iframe.getId(batch);batch.htmlfile=new window.ActiveXObject("htmlfile");batch.htmlfile.open();batch.htmlfile.write("<"+"html>");batch.htmlfile.write("<div><iframe className='wibble' src='javascript:void(0)' id='"+idname+"' name='"+idname+"' onload='dwr.engine.transport.iframe.loadingComplete("+batch.map.batchId+");'></iframe></div>");batch.htmlfile.write("</"+"html>");batch.htmlfile.close();batch.htmlfile.parentWindow.dwr=dwr;batch.document=batch.htmlfile;dwr.engine.transport.iframe.beginLoader(batch,idname);}}};dwr.engine.batch={create:function(){var batch={async:dwr.engine._async,charsProcessed:0,handlers:[],isPoll:false,map:{callCount:0,windowName:window.name},paramCount:0,preHooks:[],postHooks:[],timeout:dwr.engine._timeout,errorHandler:dwr.engine._errorHandler,warningHandler:dwr.engine._warningHandler,textHtmlHandler:dwr.engine._textHtmlHandler};if(dwr.engine._preHook){batch.preHooks.push(dwr.engine._preHook);}
if(dwr.engine._postHook){batch.postHooks.push(dwr.engine._postHook);}
dwr.engine.batch.populateHeadersAndParameters(batch);return batch;},createPoll:function(){var batch={async:true,charsProcessed:0,handlers:[{callback:function(pause){dwr.engine._pollRetries=0;setTimeout(dwr.engine._poll,pause);}}],isPoll:true,map:{windowName:window.name},paramCount:0,path:dwr.engine._pathToDwrServlet,preHooks:[],postHooks:[],timeout:0,windowName:window.name,errorHandler:dwr.engine._pollErrorHandler,warningHandler:dwr.engine._pollErrorHandler,textHtmlHandler:dwr.engine._textHtmlHandler};dwr.engine.batch.populateHeadersAndParameters(batch);return batch;},populateHeadersAndParameters:function(batch){var propname,data;batch.headers={};if(dwr.engine._headers){for(propname in dwr.engine._headers){data=dwr.engine._headers[propname];if(typeof data!="function")batch.headers[propname]=data;}}
batch.parameters={};if(dwr.engine._parameters){for(propname in dwr.engine._parameters){data=dwr.engine._parameters[propname];if(typeof data!="function")batch.parameters[propname]=data;}}},addCall:function(batch,scriptName,methodName,args){var callData,stopAt;var lastArg=args[args.length-1];if(lastArg==null||typeof lastArg=="function"){callData={callback:lastArg};stopAt=args.length-1;}
else if(typeof lastArg=="object"&&(typeof lastArg.callback=="function"||typeof lastArg.exceptionHandler=="function"||typeof lastArg.callbackHandler=="function"||typeof lastArg.errorHandler=="function"||typeof lastArg.warningHandler=="function")){callData=lastArg;stopAt=args.length-1;}
else{callData={};stopAt=args.length;}
dwr.engine.batch.merge(batch,callData);batch.handlers[batch.map.callCount]={exceptionHandler:callData.exceptionHandler,exceptionArg:callData.exceptionArg||callData.arg||null,exceptionScope:callData.exceptionScope||callData.scope||window,callback:callData.callbackHandler||callData.callback,callbackArg:callData.callbackArg||callData.arg||null,callbackScope:callData.callbackScope||callData.scope||window};var prefix="c"+batch.map.callCount+"-";batch.map[prefix+"scriptName"]=scriptName;batch.map[prefix+"methodName"]=methodName;batch.map[prefix+"id"]=batch.map.callCount;var converted=[];for(var i=0;i<stopAt;i++){dwr.engine.serialize.convert(batch,converted,args[i],prefix+"param"+i,0);}},merge:function(batch,overrides){var propname,data;for(var i=0;i<dwr.engine._propnames.length;i++){propname=dwr.engine._propnames[i];if(overrides[propname]!=null)batch[propname]=overrides[propname];}
if(overrides.preHook!=null)batch.preHooks.unshift(overrides.preHook);if(overrides.postHook!=null)batch.postHooks.push(overrides.postHook);if(overrides.headers){for(propname in overrides.headers){data=overrides.headers[propname];if(typeof data!="function")batch.headers[propname]=data;}}
if(overrides.parameters){for(propname in overrides.parameters){data=overrides.parameters[propname];if(typeof data!="function")batch.map["p-"+propname]=""+data;}}},prepareToSend:function(batch){batch.map.batchId=dwr.engine._nextBatchId;dwr.engine._nextBatchId++;dwr.engine._batches[batch.map.batchId]=batch;dwr.engine._batchesLength++;batch.completed=false;batch.map.page=encodeURIComponent(window.location.pathname+window.location.search);batch.map.httpSessionId=dwr.engine._getHttpSessionId();batch.map.scriptSessionId=dwr.engine._scriptSessionId;batch.map.windowName=window.name;for(var i=0;i<batch.preHooks.length;i++){batch.preHooks[i]();}
batch.preHooks=null;if(batch.timeout&&batch.timeout!=0){batch.timeoutId=setTimeout(function(){dwr.engine.transport.abort(batch);},batch.timeout);}},constructRequest:function(batch,httpMethod){var urlBuffer=[];urlBuffer.push(batch.path);urlBuffer.push(batch.mode);if(batch.isPoll){urlBuffer.push("ReverseAjax.dwr");}
else if(batch.map.callCount==1){urlBuffer.push(batch.map["c0-scriptName"]);urlBuffer.push(".");urlBuffer.push(batch.map["c0-methodName"]);urlBuffer.push(".dwr");}
else{urlBuffer.push("Multiple.");urlBuffer.push(batch.map.callCount);urlBuffer.push(".dwr");}
var sessionMatch=location.href.match(/jsessionid=([^?]+)/);if(sessionMatch!=null){urlBuffer.push(";jsessionid=");urlBuffer.push(sessionMatch[1]);}
var request={};var prop;if(httpMethod=="GET"){batch.map.callCount=""+batch.map.callCount;urlBuffer.push("?");for(prop in batch.map){if(typeof batch.map[prop]!="function"){urlBuffer.push(encodeURIComponent(prop));urlBuffer.push("=");urlBuffer.push(encodeURIComponent(batch.map[prop]));urlBuffer.push("&");}}
urlBuffer.pop();request.body=null;}
else{if(dwr.engine.isIE<=7){var buf=[];for(prop in batch.map){if(typeof batch.map[prop]!="function"){buf.push(prop+"="+batch.map[prop]+dwr.engine._postSeperator);}}
request.body=buf.join("");}
else{for(prop in batch.map){if(typeof batch.map[prop]!="function"){request.body+=prop+"="+batch.map[prop]+dwr.engine._postSeperator;}}}
var bodyBuffer=[];for(prop in batch.map){if(typeof batch.map[prop]!="function"){bodyBuffer.push(prop);bodyBuffer.push("=");bodyBuffer.push(batch.map[prop]);bodyBuffer.push(dwr.engine._postSeperator);}}
request.body=dwr.engine._contentRewriteHandler(bodyBuffer.join(""));}
request.url=dwr.engine._urlRewriteHandler(urlBuffer.join(""));return request;},validate:function(batch){if(!batch.completed){for(var i=0;i<batch.map.callCount;i++){if(batch.handlers[i].completed!==true){dwr.engine._handleWarning(batch,{name:"dwr.engine.incompleteReply",message:"Incomplete reply from server"});break;}}}},remove:function(batch){if(!batch){dwr.engine._debug("Warning: null batch in dwr.engine.batch.remove()",true);return;}
if(batch.completed=="true"){dwr.engine._debug("Warning: Double complete",true);return;}
batch.completed=true;dwr.engine.transport.remove(batch);if(batch.timeoutId){clearTimeout(batch.timeoutId);delete batch.timeoutId;}
if(batch.map&&(batch.map.batchId||batch.map.batchId==0)){delete dwr.engine._batches[batch.map.batchId];dwr.engine._batchesLength--;}
if(dwr.engine._batchQueue.length!=0){var sendbatch=dwr.engine._batchQueue.shift();dwr.engine.transport.send(sendbatch);}}};dwr.engine.util={newActiveXObject:function(axarray){var returnValue;for(var i=0;i<axarray.length;i++){try{returnValue=new ActiveXObject(axarray[i]);break;}
catch(ex){}}
return returnValue;}};var userAgent=navigator.userAgent;var versionString=navigator.appVersion;var version=parseFloat(versionString);dwr.engine.isOpera=(userAgent.indexOf("Opera")>=0)?version:0;dwr.engine.isKhtml=(versionString.indexOf("Konqueror")>=0)||(versionString.indexOf("Safari")>=0)?version:0;dwr.engine.isSafari=(versionString.indexOf("Safari")>=0)?version:0;dwr.engine.isJaxerServer=(window.Jaxer&&Jaxer.isOnServer);var geckoPos=userAgent.indexOf("Gecko");dwr.engine.isMozilla=((geckoPos>=0)&&(!dwr.engine.isKhtml))?version:0;dwr.engine.isFF=0;dwr.engine.isIE=0;try{if(dwr.engine.isMozilla){dwr.engine.isFF=parseFloat(userAgent.split("Firefox/")[1].split(" ")[0]);}
if((document.all)&&(!dwr.engine.isOpera)){dwr.engine.isIE=parseFloat(versionString.split("MSIE ")[1].split(";")[0]);}}
catch(ex){}
eval("");dwr.hub={publish:function(topicName,data){dwr.engine._execute(dwr.engine._pathToDwrServlet,'__System','publish',topicName,data,{});},subscribe:function(topicName,callback,scope,subscriberData){var subscription=""+dwr.hub._subscriptionId;dwr.hub._subscriptionId++;dwr.hub._subscriptions[subscription]={callback:callback,scope:scope,subscriberData:subscriberData};dwr.engine._execute(dwr.engine._pathToDwrServlet,'__System','subscribe',topicName,subscription,{});return subscription;},_remotePublish:function(subscriptionId,publishData){var subscriptionData=dwr.hub._subscriptions[subscriptionId];if(!subscriptionData)return;subscriptionData.callback.call(subscriptionData.scope,publishData,subscriptionData.subscriberData);},_subscriptionId:0,_subscriptions:{}};})();dwr.data={StoreChangeListener:{itemRemoved:function(source,itemId){},itemAdded:function(source,item){},itemChanged:function(source,item,changedAttributes){}},Cache:function(storeId,listener){this.storeId=storeId;this.listener=listener;}};(function(){dwr.data.Cache.prototype.viewRegion=function(region,callbackObj){if(!region)region={};if(!region.start)region.start=0;if(!region.count)region.count=-1;if(!region.sort)region.sort=[];if(!region.query)region.query={};return dwr.engine._execute(dwr.engine._pathToDwrServlet,'__Data','viewRegion',[this.storeId,region,this.listener,callbackObj]);};dwr.data.Cache.prototype.viewItem=function(itemId,callbackObj){return dwr.engine._execute(dwr.engine._pathToDwrServlet,'__Data','viewItem',[this.storeId,itemId,this.listener,callbackObj]);};dwr.data.Cache.prototype.unsubscribe=function(callbackObj){if(this.listener){return dwr.engine._execute(dwr.engine._pathToDwrServlet,'__Data','unsubscribe',[this.storeId,this.listener,callbackObj]);}};dwr.data.Cache.prototype.update=function(items,callbackObj){return dwr.engine._execute(dwr.engine._pathToDwrServlet,'__Data','update',[this.storeId,items,callbackObj]);};})();if(window['dojo'])dojo.provide('dwr.util');if(typeof window['dwr']=='undefined')window.dwr={};if(typeof dwr['util']=='undefined')dwr.util={};dwr.util._escapeHtml=true;dwr.util.setEscapeHtml=function(escapeHtml){dwr.util._escapeHtml=escapeHtml;};dwr.util._shouldEscapeHtml=function(options){if(options&&options.escapeHtml!=null){return options.escapeHtml;}
return dwr.util._escapeHtml;};dwr.util.escapeHtml=function(original){return original.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');};dwr.util.unescapeHtml=function(original){return original.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#039;/g,"'").replace(/&amp;/g,'&');};dwr.util.replaceXmlCharacters=function(original){original=original.replace("&","+");original=original.replace("<","\u2039");original=original.replace(">","\u203A");original=original.replace("\'","\u2018");original=original.replace("\"","\u201C");return original;};dwr.util.containsXssRiskyCharacters=function(original){return(original.indexOf('&')!=-1||original.indexOf('<')!=-1||original.indexOf('>')!=-1||original.indexOf('\'')!=-1||original.indexOf('\"')!=-1);};dwr.util.onReturn=function(event,action){if(!event)event=window.event;if(event&&event.keyCode&&event.keyCode==13)action();};dwr.util.selectRange=function(ele,start,end){ele=dwr.util._getElementById(ele,"selectRange()");if(ele==null)return;if(ele.setSelectionRange){ele.setSelectionRange(start,end);}
else if(ele.createTextRange){var range=ele.createTextRange();range.moveStart("character",start);range.moveEnd("character",end-ele.value.length);range.select();}
ele.focus();};dwr.util.byId=function(){var elems=[];for(var i=0;i<arguments.length;i++){var idOrElem=arguments[i];var elem;if(typeof idOrElem=='string'){var elem=document.getElementById(idOrElem);if(document.all&&elem&&elem.attributes.id.value!=idOrElem){elem=null;var maybeElems=document.all[idOrElem];if(maybeElems.tagName)maybeElems=[maybeElems];for(var j=0;j<maybeElems.length;j++){if(maybeElems[j].attributes.id.value==idOrElem){elem=maybeElems[j];break;}}}}
else{elem=idOrElem;}
if(arguments.length==1){return elem;}
elems.push(elem);}
return elems;}
if(window['$']==null){window['$']=dwr.util.byId;}
dwr.util.toDescriptiveString=function(data,showLevels,options){if(showLevels===undefined)showLevels=1;var opt={};if(dwr.util._isObject(options))opt=options;var defaultoptions={escapeHtml:false,baseIndent:"",childIndent:"\u00A0\u00A0",lineTerminator:"\n",oneLineMaxItems:5,shortStringMaxLength:13,propertyNameMaxLength:30};for(var p in defaultoptions){if(!(p in opt)){opt[p]=defaultoptions[p];}}
var skipDomProperties={document:true,ownerDocument:true,all:true,parentElement:true,parentNode:true,offsetParent:true,children:true,firstChild:true,lastChild:true,previousSibling:true,nextSibling:true,innerHTML:true,outerHTML:true,innerText:true,outerText:true,textContent:true,attributes:true,style:true,currentStyle:true,runtimeStyle:true,parentTextEdit:true};function recursive(data,showLevels,indentDepth,options){var reply="";try{if(dwr.util._isString(data)){var str=data;if(showLevels==0&&str.length>options.shortStringMaxLength)
str=str.substring(0,options.shortStringMaxLength-3)+"...";if(options.escapeHtml){var lines=str.split("\n");for(var i=0;i<lines.length;i++)lines[i]=dwr.util.escapeHtml(lines[i]);str=lines.join("\n");}
if(showLevels==0){str=str.replace(/\n|\r|\t/g,function(ch){switch(ch){case"\n":return"\\n";case"\r":return"";case"\t":return"\\t";}});}
else{str=str.replace(/\n|\r|\t/g,function(ch){switch(ch){case"\n":return options.lineTerminator+indent(indentDepth+1,options);case"\r":return"";case"\t":return"\\t";}});}
reply='"'+str+'"';}
else if(dwr.util._isFunction(data)){reply="function";}
else if(dwr.util._isArrayLike(data)){if(showLevels==0){if(data.length>0)
reply="[...]";else
reply="[]";}
else{var strarr=[];strarr.push("[");var count=0;for(var i=0;i<data.length;i++){if(!(i in data)&&data!="[object NodeList]")continue;var itemvalue=data[i];if(count>0)strarr.push(", ");if(showLevels==1){if(count==options.oneLineMaxItems){strarr.push("...");break;}}
else{strarr.push(options.lineTerminator+indent(indentDepth+1,options));}
if(i!=count){strarr.push(i);strarr.push(":");}
strarr.push(recursive(itemvalue,showLevels-1,indentDepth+1,options));count++;}
if(showLevels>1)strarr.push(options.lineTerminator+indent(indentDepth,options));strarr.push("]");reply=strarr.join("");}}
else if(dwr.util._isObject(data)&&!dwr.util._isDate(data)){if(showLevels==0){reply=dwr.util._detailedTypeOf(data);}
else{var strarr=[];if(dwr.util._detailedTypeOf(data)!="Object"){strarr.push(dwr.util._detailedTypeOf(data));if(typeof data.valueOf()!="object"){strarr.push(":");strarr.push(recursive(data.valueOf(),1,indentDepth,options));}
strarr.push(" ");}
strarr.push("{");var isDomObject=dwr.util._isHTMLElement(data);var count=0;for(var prop in data){var propvalue=data[prop];if(isDomObject){if(!propvalue)continue;if(typeof propvalue=="function")continue;if(skipDomProperties[prop])continue;if(prop.toUpperCase()==prop)continue;}
if(count>0)strarr.push(", ");if(showLevels==1){if(count==options.oneLineMaxItems){strarr.push("...");break;}}
else{strarr.push(options.lineTerminator+indent(indentDepth+1,options));}
strarr.push(prop.length>options.propertyNameMaxLength?prop.substring(0,options.propertyNameMaxLength-3)+"...":prop);strarr.push(":");strarr.push(recursive(propvalue,showLevels-1,indentDepth+1,options));count++;}
if(showLevels>1&&count>0)strarr.push(options.lineTerminator+indent(indentDepth,options));strarr.push("}");reply=strarr.join("");}}
else{reply=""+data;}
return reply;}
catch(err){return(err.message?err.message:""+err);}}
function indent(count,options){var strarr=[];strarr.push(options.baseIndent);for(var i=0;i<count;i++){strarr.push(options.childIndent);}
return strarr.join("");};return recursive(data,showLevels,0,opt);};dwr.util.useLoadingMessage=function(message){var loadingMessage;if(message)loadingMessage=message;else loadingMessage="Loading";dwr.engine.setPreHook(function(){var disabledZone=dwr.util.byId('disabledZone');if(!disabledZone){disabledZone=document.createElement('div');disabledZone.setAttribute('id','disabledZone');disabledZone.style.position="absolute";disabledZone.style.zIndex="1000";disabledZone.style.left="0px";disabledZone.style.top="0px";disabledZone.style.width="100%";disabledZone.style.height="100%";if(window.ActiveXObject){disabledZone.style.background="white";disabledZone.style.filter="alpha(opacity=0)";}
document.body.appendChild(disabledZone);var messageZone=document.createElement('div');messageZone.setAttribute('id','messageZone');messageZone.style.position="absolute";messageZone.style.top="0px";messageZone.style.right="0px";messageZone.style.background="red";messageZone.style.color="white";messageZone.style.fontFamily="Arial,Helvetica,sans-serif";messageZone.style.padding="4px";document.body.appendChild(messageZone);var text=document.createTextNode(loadingMessage);messageZone.appendChild(text);dwr.util._disabledZoneUseCount=1;}
else{dwr.util.byId('messageZone').innerHTML=loadingMessage;disabledZone.style.visibility='visible';dwr.util._disabledZoneUseCount++;dwr.util.byId('messageZone').style.visibility='visible';}});dwr.engine.setPostHook(function(){dwr.util._disabledZoneUseCount--;if(dwr.util._disabledZoneUseCount==0){dwr.util.byId('disabledZone').style.visibility='hidden';dwr.util.byId('messageZone').style.visibility='hidden';}});};dwr.util.setHighlightHandler=function(handler){dwr.util._highlightHandler=handler;};dwr.util.yellowFadeHighlightHandler=function(ele){dwr.util._yellowFadeProcess(ele,0);};dwr.util._yellowFadeSteps=["d0","b0","a0","90","98","a0","a8","b0","b8","c0","c8","d0","d8","e0","e8","f0","f8"];dwr.util._yellowFadeProcess=function(ele,colorIndex){ele=dwr.util.byId(ele);if(colorIndex<dwr.util._yellowFadeSteps.length){ele.style.backgroundColor="#ffff"+dwr.util._yellowFadeSteps[colorIndex];setTimeout("dwr.util._yellowFadeProcess('"+ele.id+"',"+(colorIndex+1)+")",200);}
else{ele.style.backgroundColor="transparent";}};dwr.util.borderFadeHighlightHandler=function(ele){ele.style.borderWidth="2px";ele.style.borderStyle="solid";dwr.util._borderFadeProcess(ele,0);};dwr.util._borderFadeSteps=["d0","b0","a0","90","98","a0","a8","b0","b8","c0","c8","d0","d8","e0","e8","f0","f8"];dwr.util._borderFadeProcess=function(ele,colorIndex){ele=dwr.util.byId(ele);if(colorIndex<dwr.util._borderFadeSteps.length){ele.style.borderColor="#ff"+dwr.util._borderFadeSteps[colorIndex]+dwr.util._borderFadeSteps[colorIndex];setTimeout("dwr.util._borderFadeProcess('"+ele.id+"',"+(colorIndex+1)+")",200);}
else{ele.style.backgroundColor="transparent";}};dwr.util.focusHighlightHandler=function(ele){try{ele.focus();}
catch(ex){}};dwr.util._highlightHandler=null;dwr.util.highlight=function(ele,options){if(options&&options.highlightHandler){options.highlightHandler(dwr.util.byId(ele));}
else if(dwr.util._highlightHandler!=null){dwr.util._highlightHandler(dwr.util.byId(ele));}};dwr.util.setValue=function(ele,val,options){if(val==null)val="";if(options==null)options={};var orig=ele;ele=dwr.util.byId(ele);var nodes=null;if(ele==null){nodes=document.getElementsByName(orig);if(nodes.length>=1)ele=nodes.item(0);}
if(ele==null){dwr.util._debug("setValue() can't find an element with id/name: "+orig+".");return;}
dwr.util.highlight(ele,options);if(dwr.util._isHTMLElement(ele,"select")){if(ele.type=="select-multiple"&&dwr.util._isArray(val))dwr.util._selectListItems(ele,val);else dwr.util._selectListItem(ele,val);return;}
if(dwr.util._isHTMLElement(ele,"input")){if(ele.type=="radio"||ele.type=="checkbox"){if(nodes&&nodes.length>=1){for(var i=0;i<nodes.length;i++){var node=nodes.item(i);if(node.type!=ele.type)continue;if(dwr.util._isArray(val)){node.checked=false;for(var j=0;j<val.length;j++)
if(val[j]==node.value)node.checked=true;}
else{node.checked=(node.value==val);}}}
else{ele.checked=(val==true);}}
else ele.value=val;return;}
if(dwr.util._isHTMLElement(ele,"textarea")){ele.value=val;return;}
if(dwr.util._isHTMLElement(ele,"img")){ele.src=val;return;}
if(val.nodeType){if(val.nodeType==9)val=val.documentElement;val=dwr.util._importNode(ele.ownerDocument,val,true);ele.appendChild(val);return;}
if(dwr.util._shouldEscapeHtml(options)){if("textContent"in ele)ele.textContent=val.toString();else if("innerText"in ele)ele.innerText=val.toString();else ele.innerHTML=dwr.util.escapeHtml(val.toString());}
else{ele.innerHTML=val;}};dwr.util._selectListItems=function(ele,val){var found=0;var i;var j;for(i=0;i<ele.options.length;i++){ele.options[i].selected=false;for(j=0;j<val.length;j++){if(ele.options[i].value==val[j]){ele.options[i].selected=true;found++;}}}
if(found==val.length)return;for(i=0;i<ele.options.length;i++){for(j=0;j<val.length;j++){if(ele.options[i].text==val[j]){ele.options[i].selected=true;}}}};dwr.util._selectListItem=function(ele,val){var found=false;var i;for(i=0;i<ele.options.length;i++){if(ele.options[i].value==val){ele.options[i].selected=true;found=true;}
else{ele.options[i].selected=false;}}
if(found)return;for(i=0;i<ele.options.length;i++){ele.options[i].selected=(ele.options[i].text==val);}};dwr.util.getValue=function(ele,options){if(options==null)options={};var orig=ele;ele=dwr.util.byId(ele);var nodes=null;if(ele==null){nodes=document.getElementsByName(orig);if(nodes.length>=1)ele=nodes.item(0);}
if(ele==null){dwr.util._debug("getValue() can't find an element with id/name: "+orig+".");return"";}
if(dwr.util._isHTMLElement(ele,"select")){if(ele.type=="select-multiple"){var reply=new Array();for(var i=0;i<ele.options.length;i++){var item=ele.options[i];if(item.selected){var valueAttr=item.getAttributeNode("value");if(valueAttr&&valueAttr.specified){reply.push(item.value);}
else{reply.push(item.text);}}}
return reply;}
else{var sel=ele.selectedIndex;if(sel!=-1){var item=ele.options[sel];var valueAttr=item.getAttributeNode("value");if(valueAttr&&valueAttr.specified){return item.value;}
return item.text;}
else{return"";}}}
if(dwr.util._isHTMLElement(ele,"input")){if(ele.type=="radio"){if(nodes&&nodes.length>=1){for(var i=0;i<nodes.length;i++){var node=nodes.item(i);if(node.type==ele.type){if(node.checked)return node.value;}}}
return ele.checked;}
if(ele.type=="checkbox"){if(nodes&&nodes.length>=1){var reply=[];for(var i=0;i<nodes.length;i++){var node=nodes.item(i);if(node.type==ele.type){if(node.checked)reply.push(node.value);}}
return reply;}
return ele.checked;}
if(ele.type=="file"){return ele;}
return ele.value;}
if(dwr.util._isHTMLElement(ele,"textarea")){return ele.value;}
if(dwr.util._shouldEscapeHtml(options)){if(ele.textContent)return ele.textContent;else if(ele.innerText)return ele.innerText;}
return ele.innerHTML;};dwr.util.getText=function(ele){ele=dwr.util._getElementById(ele,"getText()");if(ele==null)return null;if(!dwr.util._isHTMLElement(ele,"select")){dwr.util._debug("getText() can only be used with select elements. Attempt to use: "+dwr.util._detailedTypeOf(ele)+" from  id: "+orig+".");return"";}
var sel=ele.selectedIndex;if(sel!=-1){return ele.options[sel].text;}
else{return"";}};dwr.util.setValues=function(data,options){var prefix="";var depth=100;if(options&&options.prefix)prefix=options.prefix;if(options&&options.idPrefix)prefix=options.idPrefix;if(options&&"depth"in options)depth=options.depth;dwr.util._setValuesRecursive(data,prefix,depth,options);};dwr.util._setValuesRecursive=function(data,idpath,depth,options){if(depth==0)return;if(dwr.util._isArray(data)&&data.length>0&&dwr.util._isObject(data[0])){for(var i=0;i<data.length;i++){dwr.util._setValuesRecursive(data[i],idpath+"["+i+"]",depth-1,options);}}
else if(dwr.util._isObject(data)&&!dwr.util._isArray(data)){for(var prop in data){var subidpath=idpath?idpath+"."+prop:prop;if(dwr.util._isObject(data[prop])&&!dwr.util._isArray(data[prop])&&!dwr.util._isDate(data[prop])||dwr.util._isArray(data[prop])&&data[prop].length>0&&dwr.util._isObject(data[prop][0])){dwr.util._setValuesRecursive(data[prop],subidpath,depth-1,options);}
else if(typeof data[prop]=="function"){}
else{if(dwr.util.byId(subidpath)!=null||document.getElementsByName(subidpath).length>=1){dwr.util.setValue(subidpath,data[prop],options);}}}}};dwr.util.getValues=function(data,options){if(typeof data=="string"||dwr.util._isHTMLElement(data)){return dwr.util.getFormValues(data);}
else{var prefix="";var depth=100;if(options!=null&&options.prefix)prefix=options.prefix;if(options!=null&&options.idPrefix)prefix=options.idPrefix;if(options!=null&&"depth"in options)depth=options.depth;dwr.util._getValuesRecursive(data,prefix,depth,options);return data;}};dwr.util.getFormValues=function(eleOrNameOrId){var ele=null;if(typeof eleOrNameOrId=="string"){ele=document.forms[eleOrNameOrId];if(ele==null)ele=dwr.util.byId(eleOrNameOrId);}
else if(dwr.util._isHTMLElement(eleOrNameOrId)){ele=eleOrNameOrId;}
if(ele!=null){if(ele.elements==null){alert("getFormValues() requires an object or reference to a form element.");return null;}
var reply={};var name;var value;for(var i=0;i<ele.elements.length;i++){if(ele[i].type in{button:0,submit:0,reset:0,image:0,file:0})continue;if(ele[i].name){name=ele[i].name;value=dwr.util.getValue(name);}
else{if(ele[i].id)name=ele[i].id;else name="element"+i;value=dwr.util.getValue(ele[i]);}
reply[name]=value;}
return reply;}};dwr.util._getValuesRecursive=function(data,idpath,depth,options){if(depth==0)return;if(dwr.util._isArray(data)&&data.length>0&&dwr.util._isObject(data[0])){for(var i=0;i<data.length;i++){dwr.util._getValuesRecursive(data[i],idpath+"["+i+"]",depth-1,options);}}
else if(dwr.util._isObject(data)&&!dwr.util._isArray(data)){for(var prop in data){var subidpath=idpath?idpath+"."+prop:prop;if(dwr.util._isObject(data[prop])&&!dwr.util._isArray(data[prop])||dwr.util._isArray(data[prop])&&data[prop].length>0&&dwr.util._isObject(data[prop][0])){dwr.util._getValuesRecursive(data[prop],subidpath,depth-1,options);}
else if(typeof data[prop]=="function"){}
else{if(dwr.util.byId(subidpath)!=null||document.getElementsByName(subidpath).length>=1){data[prop]=dwr.util.getValue(subidpath);}}}}};dwr.util.addOptions=function(ele,data){ele=dwr.util._getElementById(ele,"addOptions()");if(ele==null)return;var useOptions=dwr.util._isHTMLElement(ele,"select");var useLi=dwr.util._isHTMLElement(ele,["ul","ol"]);if(!useOptions&&!useLi){dwr.util._debug("addOptions() can only be used with select/ul/ol elements. Attempt to use: "+dwr.util._detailedTypeOf(ele));return;}
if(data==null)return;var argcount=arguments.length;var options={};var lastarg=arguments[argcount-1];if(argcount>2&&dwr.util._isObject(lastarg)){options=lastarg;argcount--;}
var arg3=null;if(argcount>=3)arg3=arguments[2];var arg4=null;if(argcount>=4)arg4=arguments[3];if(!options.optionCreator&&useOptions)options.optionCreator=dwr.util._defaultOptionCreator;if(!options.optionCreator&&useLi)options.optionCreator=dwr.util._defaultListItemCreator;options.document=ele.ownerDocument;var text,value,li;if(dwr.util._isArray(data)){for(var i=0;i<data.length;i++){options.data=data[i];options.text=null;options.value=null;if(useOptions){if(arg3!=null){if(arg4!=null){options.text=dwr.util._getValueFrom(data[i],arg4);options.value=dwr.util._getValueFrom(data[i],arg3);}
else options.text=options.value=dwr.util._getValueFrom(data[i],arg3);}
else options.text=options.value=dwr.util._getValueFrom(data[i]);if(options.text!=null||options.value){var opt=options.optionCreator(options);opt.text=options.text;opt.value=options.value;ele.options[ele.options.length]=opt;}}
else{options.value=dwr.util._getValueFrom(data[i],arg3);if(options.value!=null){li=options.optionCreator(options);if(dwr.util._shouldEscapeHtml(options)){options.value=dwr.util.escapeHtml(options.value);}
li.innerHTML=options.value;ele.appendChild(li);}}}}
else if(arg4!=null){if(!useOptions){alert("dwr.util.addOptions can only create select lists from objects.");return;}
for(var prop in data){options.data=data[prop];options.value=dwr.util._getValueFrom(data[prop],arg3);options.text=dwr.util._getValueFrom(data[prop],arg4);if(options.text!=null||options.value){var opt=options.optionCreator(options);opt.text=options.text;opt.value=options.value;ele.options[ele.options.length]=opt;}}}
else{if(!useOptions){dwr.util._debug("dwr.util.addOptions can only create select lists from objects.");return;}
for(var prop in data){if(typeof data[prop]=="function")continue;options.data=data[prop];if(!arg3){options.value=prop;options.text=data[prop];}
else{options.value=data[prop];options.text=prop;}
if(options.text!=null||options.value){var opt=options.optionCreator(options);opt.text=options.text;opt.value=options.value;ele.options[ele.options.length]=opt;}}}
dwr.util.highlight(ele,options);};dwr.util._getValueFrom=function(data,method){if(method==null)return data;else if(typeof method=='function')return method(data);else return data[method];};dwr.util._defaultOptionCreator=function(options){return options.document.createElement("option");};dwr.util._defaultListItemCreator=function(options){return options.document.createElement("li");};dwr.util.removeAllOptions=function(ele){ele=dwr.util._getElementById(ele,"removeAllOptions()");if(ele==null)return;var useOptions=dwr.util._isHTMLElement(ele,"select");var useLi=dwr.util._isHTMLElement(ele,["ul","ol"]);if(!useOptions&&!useLi){dwr.util._debug("removeAllOptions() can only be used with select, ol and ul elements. Attempt to use: "+dwr.util._detailedTypeOf(ele));return;}
if(useOptions){ele.options.length=0;}
else{while(ele.childNodes.length>0){ele.removeChild(ele.firstChild);}}};dwr.util.addRows=function(ele,data,cellFuncs,options){ele=dwr.util._getElementById(ele,"addRows()");if(ele==null)return;if(!dwr.util._isHTMLElement(ele,["table","tbody","thead","tfoot"])){dwr.util._debug("addRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(ele));return;}
if(!options)options={};if(!options.rowCreator)options.rowCreator=dwr.util._defaultRowCreator;if(!options.cellCreator)options.cellCreator=dwr.util._defaultCellCreator;options.document=ele.ownerDocument;var tr,rowNum;if(dwr.util._isArray(data)){for(rowNum=0;rowNum<data.length;rowNum++){options.rowData=data[rowNum];options.rowIndex=rowNum;options.rowNum=rowNum;options.data=null;options.cellNum=-1;tr=dwr.util._addRowInner(cellFuncs,options);if(tr!=null)ele.appendChild(tr);}}
else if(typeof data=="object"){rowNum=0;for(var rowIndex in data){options.rowData=data[rowIndex];options.rowIndex=rowIndex;options.rowNum=rowNum;options.data=null;options.cellNum=-1;tr=dwr.util._addRowInner(cellFuncs,options);if(tr!=null)ele.appendChild(tr);rowNum++;}}
dwr.util.highlight(ele,options);};dwr.util._emptyTableCellReplacement="<div style='width:0;height:0;overflow:hidden;'></div>";dwr.util._addRowInner=function(cellFuncs,options){var tr=options.rowCreator(options);if(tr==null)return null;for(var cellNum=0;cellNum<cellFuncs.length;cellNum++){var func=cellFuncs[cellNum];if(typeof func=='function')options.data=func(options.rowData,options);else options.data=func||"";options.cellNum=cellNum;var td=options.cellCreator(options);if(td!=null){if(options.data){if(dwr.util._isHTMLElement(options.data))td.appendChild(options.data);else{if(dwr.util._shouldEscapeHtml(options)&&typeof(options.data)=="string"){td.innerHTML=dwr.util.escapeHtml(options.data);}
else{td.innerHTML=options.data;}}}
else{td.innerHTML=dwr.util._emptyTableCellReplacement;}
tr.appendChild(td);}}
return tr;};dwr.util._defaultRowCreator=function(options){return options.document.createElement("tr");};dwr.util._defaultCellCreator=function(options){return options.document.createElement("td");};dwr.util.removeAllRows=function(ele,options){ele=dwr.util._getElementById(ele,"removeAllRows()");if(ele==null)return;if(!options)options={};if(!options.filter)options.filter=function(){return true;};if(!dwr.util._isHTMLElement(ele,["table","tbody","thead","tfoot"])){dwr.util._debug("removeAllRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(ele));return;}
var child=ele.firstChild;var next;while(child!=null){next=child.nextSibling;if(options.filter(child)){ele.removeChild(child);}
child=next;}};dwr.util.setClassName=function(ele,className){ele=dwr.util._getElementById(ele,"setClassName()");if(ele==null)return;ele.className=className;};dwr.util.addClassName=function(ele,className){ele=dwr.util._getElementById(ele,"addClassName()");if(ele==null)return;ele.className+=" "+className;};dwr.util.removeClassName=function(ele,className){ele=dwr.util._getElementById(ele,"removeClassName()");if(ele==null)return;var regex=new RegExp("(^|\\s)"+className+"(\\s|$)",'g');ele.className=ele.className.replace(regex,'');};dwr.util.toggleClassName=function(ele,className){ele=dwr.util._getElementById(ele,"toggleClassName()");if(ele==null)return;var regex=new RegExp("(^|\\s)"+className+"(\\s|$)");if(regex.test(ele.className)){ele.className=ele.className.replace(regex,'');}
else{ele.className+=" "+className;}};dwr.util.cloneNode=function(ele,options){ele=dwr.util._getElementById(ele,"cloneNode()");if(ele==null)return null;if(options==null)options={};var clone=ele.cloneNode(true);if(options.idPrefix||options.idSuffix){dwr.util._updateIds(clone,options);}
else{dwr.util._removeIds(clone);}
ele.parentNode.insertBefore(clone,ele);return clone;};dwr.util._updateIds=function(ele,options){if(options==null)options={};if(ele.id){ele.setAttribute("id",(options.idPrefix||"")+ele.id+(options.idSuffix||""));}
var children=ele.childNodes;for(var i=0;i<children.length;i++){var child=children.item(i);if(child.nodeType==1){dwr.util._updateIds(child,options);}}};dwr.util._removeIds=function(ele){if(ele.id)ele.removeAttribute("id");var children=ele.childNodes;for(var i=0;i<children.length;i++){var child=children.item(i);if(child.nodeType==1){dwr.util._removeIds(child);}}};dwr.util.cloneNodeForValues=function(templateEle,data,options){templateEle=dwr.util._getElementById(templateEle,"cloneNodeForValues()");if(templateEle==null)return null;if(options==null)options={};var idpath;if(options.idPrefix!=null)
idpath=options.idPrefix;else
idpath=templateEle.id||"";return dwr.util._cloneNodeForValuesRecursive(templateEle,data,idpath,options);};dwr.util._cloneNodeForValuesRecursive=function(templateEle,data,idpath,options){if(dwr.util._isArray(data)){var clones=[];for(var i=0;i<data.length;i++){var item=data[i];var clone=dwr.util._cloneNodeForValuesRecursive(templateEle,item,idpath+"["+i+"]",options);clones.push(clone);}
return clones;}
else
if(dwr.util._isObject(data)&&!dwr.util._isArray(data)){var clone=templateEle.cloneNode(true);if(options.updateCloneStyle&&clone.style){for(var propname in options.updateCloneStyle){clone.style[propname]=options.updateCloneStyle[propname];}}
dwr.util._replaceIds(clone,templateEle.id,idpath);templateEle.parentNode.insertBefore(clone,templateEle);dwr.util._cloneSubArrays(data,idpath,options);return clone;}
return null;};dwr.util._replaceIds=function(ele,oldidpath,newidpath){if(ele.id){var newId=null;if(ele.id==oldidpath){newId=newidpath;}
else if(ele.id.length>oldidpath.length){if(ele.id.substr(0,oldidpath.length)==oldidpath){var trailingChar=ele.id.charAt(oldidpath.length);if(trailingChar=="."||trailingChar=="["){newId=newidpath+ele.id.substr(oldidpath.length);}}}
if(newId){ele.setAttribute("id",newId);}
else{ele.removeAttribute("id");}}
var children=ele.childNodes;for(var i=0;i<children.length;i++){var child=children.item(i);if(child.nodeType==1){dwr.util._replaceIds(child,oldidpath,newidpath);}}};dwr.util._cloneSubArrays=function(data,idpath,options){for(prop in data){var value=data[prop];if(dwr.util._isArray(value)){if(value.length>0&&dwr.util._isObject(value[0])){var subTemplateId=idpath+"."+prop;var subTemplateEle=dwr.util.byId(subTemplateId);if(subTemplateEle!=null){dwr.util._cloneNodeForValuesRecursive(subTemplateEle,value,subTemplateId,options);}}}
else if(dwr.util._isObject(value)){dwr.util._cloneSubArrays(value,idpath+"."+prop,options);}}};dwr.util._getElementById=function(ele,source){var orig=ele;ele=dwr.util.byId(ele);if(ele==null){dwr.util._debug(source+" can't find an element with id: "+orig+".");}
return ele;};dwr.util._isHTMLElement=function(ele,nodeName){if(ele==null||typeof ele!="object"||ele.nodeName==null){return false;}
if(nodeName!=null){var test=ele.nodeName.toLowerCase();if(typeof nodeName=="string"){return test==nodeName.toLowerCase();}
if(dwr.util._isArray(nodeName)){var match=false;for(var i=0;i<nodeName.length&&!match;i++){if(test==nodeName[i].toLowerCase()){match=true;}}
return match;}
dwr.util._debug("dwr.util._isHTMLElement was passed test node name that is neither a string or array of strings");return false;}
return true;};dwr.util._detailedTypeOf=function(x){var reply=typeof x;if(reply=="object"){reply=Object.prototype.toString.apply(x);reply=reply.substring(8,reply.length-1);}
return reply;};dwr.util._isObject=function(data){return(data&&typeof data=="object");};dwr.util._isArray=function(data){return(data&&Object.prototype.toString.call(data)=="[object Array]");};dwr.util._isArrayLike=function(data){return data&&(typeof data.length=="number")&&((data.propertyIsEnumerable&&data.propertyIsEnumerable("length")==false)||!data.constructor||data!="[object Object]")&&!dwr.util._isString(data)&&!dwr.util._isFunction(data)&&!data.tagName;};dwr.util._isString=function(data){return(data&&(typeof data=="string"||Object.prototype.toString.call(data)=="[object String]"));};dwr.util._isFunction=function(data){return(data&&(typeof data=="function"||Object.prototype.toString.call(data)=="[object Function]")&&data!="[object NodeList]");};dwr.util._isDate=function(data){return(data&&Object.prototype.toString.call(data)=="[object Date]");};dwr.util._importNode=function(doc,importedNode,deep){var newNode;if(importedNode.nodeType==1){newNode=doc.createElement(importedNode.nodeName);for(var i=0;i<importedNode.attributes.length;i++){var attr=importedNode.attributes[i];if(attr.nodeValue!=null&&attr.nodeValue!=''){newNode.setAttribute(attr.name,attr.nodeValue);}}
if(importedNode.style!=null){newNode.style.cssText=importedNode.style.cssText;}}
else if(importedNode.nodeType==3){newNode=doc.createTextNode(importedNode.nodeValue);}
if(deep&&importedNode.hasChildNodes()){for(i=0;i<importedNode.childNodes.length;i++){newNode.appendChild(dwr.util._importNode(doc,importedNode.childNodes[i],true));}}
return newNode;};dwr.util._debug=function(message,stacktrace){var written=false;try{if(window.console){if(stacktrace&&window.console.trace)window.console.trace();window.console.log(message);written=true;}
else if(window.opera&&window.opera.postError){window.opera.postError(message);written=true;}}
catch(ex){}
if(!written){var debug=document.getElementById("dwr-debug");if(debug){var contents=message+"<br/>"+debug.innerHTML;if(contents.length>2048)contents=contents.substring(0,2048);debug.innerHTML=contents;}}};if(typeof this['dwr']=='undefined')this.dwr={};if(typeof dwr['engine']=='undefined')dwr.engine={};if(typeof dwr.engine['_mappedClasses']=='undefined')dwr.engine._mappedClasses={};if(typeof this['dwr']=='undefined')this.dwr={};if(typeof dwr['engine']=='undefined')dwr.engine={};if(typeof dwr.engine['_mappedClasses']=='undefined')dwr.engine._mappedClasses={};if(window['dojo'])dojo.provide('dwr.interface.loggedInStatus');if(typeof this['loggedInStatus']=='undefined')loggedInStatus={};loggedInStatus._path=''+JAWR.jawr_dwr_path+'';loggedInStatus.getStatus=function(callback){return dwr.engine._execute(loggedInStatus._path,'loggedInStatus','getStatus',arguments);};function createDWRValidator(name,remoteFunction,defaultMessage){if(typeof(jQuery.validator)==='undefined'){throw"jQuery.validator.not.found";}
var validateFunction=function(value,element,param){var callback,previous,validator=this;if(this.optional(element)){return"dependency-mismatch";}
if(!this.settings.messages[element.name]){this.settings.messages[element.name]={};}
previous=this.previousValue(element);previous.originalMessage=this.settings.messages[element.name][name];this.settings.messages[element.name][name]=previous.message;if(name===previous.validatorName&&previous.old===value){return previous.valid;}
if(this.pending[element.name]){return"pending";}
previous.old=value;previous.validatorName=name;this.startRequest(element);callback=function(response){var valid,errors,message;validator.settings.messages[element.name][name]=previous.originalMessage;valid=response===true;if(valid){validator.prepareElement(element);validator.successList.push(element);validator.showErrors();}else{errors={};message=(previous.message=response||validator.defaultMessage(element,name));errors[element.name]=jQuery.isFunction(message)?message(value):message;validator.showErrors(errors);}
previous.valid=valid;validator.stopRequest(element,valid);};remoteFunction(value,callback);return"pending";};if(jQuery.validator.addedDWRRemote){throw"Only one DWR validator may be registered";}
else{jQuery.validator.addMethod(name,validateFunction,defaultMessage);jQuery.validator.addedDWRRemote=true;}}